// Canonical executable source for the V2 implementation program.
// `program.json` is an early malformed draft and is explicitly superseded by
// MODEL_MANIFEST.json. The compiler emits deterministic JSON projections.

const t = ({ id, phase, objective, why, status = 'PROPOSED', deps = [], owner, risk = 'HIGH', files = [], tests = [], rollback }) => ({
  id,
  objective,
  why,
  inputs: ['exact live state', 'applicable contracts and decisions'],
  outputs: [`evidence-backed output for ${id}`],
  dependencies: deps,
  affectedNodes: [`phase:${phase.slice(1)}`],
  affectedEdges: [],
  affectedFiles: files,
  ownerType: owner,
  risk,
  implementationSteps: ['reconstruct live prerequisites', 'make the smallest reversible change', 'verify, attack and generalize failures', 'persist evidence and state'],
  tests: tests.length ? tests : [`TST-${id}`],
  adversarialTests: [`ADV-${id}`],
  securityTests: [`SEC-${id}`],
  evidenceRequired: ['exact source revision', 'commands or review performed', 'results with PASS/FAIL/SKIPPED/NOT_RUN', 'artifact hashes'],
  rollback,
  definitionOfDone: ['implementation exists', 'applicable tests executed and passed', 'security reviewed', 'documentation/state/graph updated', 'evidence bound to exact revision', 'zero-context handoff possible'],
  status,
});

export const program = {
  schemaVersion: 1,
  programId: 'program_cos_authority_10',
  northStarId: 'northstar:20d10',
  revision: 2,
  generatedAt: '2026-08-30T17:30:00.000Z',
  sourceRevision: '1bc137eb6e635f55db293b402f561e420dc83c4f',
  definitionOfDone: {
    program: [
      'D01 through D20 each have Authority 10.0 backed by exact-SHA evidence',
      'no open P0 or P1 defect',
      'replay, empty-database restore, cold-agent resume and security gauntlet pass',
      'single authority writer exists for every stateful capability',
      'main convergence is reviewed, reversible and merged with expected SHA',
      'GitHub, Drive and Todoist final states agree',
    ],
    task: ['implementation', 'executed tests', 'security review', 'durable evidence', 'rollback', 'zero-context handoff'],
  },
  phases: [
    { id: 'P00', nodeId: 'phase:00', name: 'North Star and control plane', status: 'ACTIVE', checkpoint: 'CP1', waves: [
      { id: 'W00.1', name: 'Live truth and session barrier', tasks: ['T0001','T0002','T0003'] },
      { id: 'W00.2', name: 'Hypergraph and compiler', tasks: ['T0004','T0005','T0006'] },
      { id: 'W00.3', name: 'Continuity projection', tasks: ['T0007','T0008'] },
    ]},
    { id: 'P01', nodeId: 'phase:01', name: 'Canonical reconciliation', status: 'COMPLETE_STATIC_UNVERIFIED', checkpoint: 'CP3', waves: [{ id: 'W01.1', name: 'Lineage convergence', tasks: ['T0101'] }] },
    { id: 'P02', nodeId: 'phase:02', name: 'Contracts, compatibility and deletion governance', status: 'COMPLETE_STATIC_UNVERIFIED', checkpoint: 'CP5', waves: [{ id: 'W02.1', name: 'Contract governance', tasks: ['T0201','T0202'] }] },
    { id: 'P03', nodeId: 'phase:03', name: 'Core correctness', status: 'COMPLETE_STATIC_UNVERIFIED', checkpoint: 'CP6', waves: [{ id: 'W03.1', name: 'Core invariant proof', tasks: ['T0301','T0302'] }] },
    { id: 'P04', nodeId: 'phase:04', name: 'Temporal, event and persistence', status: 'COMPLETE_STATIC_UNVERIFIED', checkpoint: 'CP7', waves: [{ id: 'W04.1', name: 'Durability and recovery', tasks: ['T0401','T0402'] }] },
    { id: 'P05', nodeId: 'phase:05', name: 'Security, concurrency and agent runtime', status: 'ACTIVE_IMPLEMENTED_UNVERIFIED', checkpoint: 'CP10', waves: [
      { id: 'W05.1', name: 'Provider evidence and isolation closure', tasks: ['T0501','T0502','T0503'] },
      { id: 'W05.2', name: 'Durable coordination and observation', tasks: ['T0504','T0505'] },
    ]},
    { id: 'P06', nodeId: 'phase:06', name: 'Hub, memory, GraphRAG and observability', status: 'PARTIAL_IMPLEMENTED_UNVERIFIED', checkpoint: 'CP11', waves: [
      { id: 'W06.1', name: 'Context and memory authority', tasks: ['T0601','T0602'] },
      { id: 'W06.2', name: 'Gold path and telemetry', tasks: ['T0603','T0604'] },
    ]},
    { id: 'P07', nodeId: 'phase:07', name: 'Test truth and manual CI', status: 'PROPOSED', checkpoint: 'CP9', waves: [{ id: 'W07.1', name: 'Clean toolchain and full matrix', tasks: ['T0701','T0702','T0703'] }] },
    { id: 'P08', nodeId: 'phase:08', name: 'Evidence campaign', status: 'PROPOSED', checkpoint: 'CP12', waves: [{ id: 'W08.1', name: 'Adversarial assurance', tasks: ['T0801','T0802','T0803','T0804'] }] },
    { id: 'P09', nodeId: 'phase:09', name: 'Authority qualification and merge', status: 'BLOCKED', checkpoint: 'CP14', waves: [{ id: 'W09.1', name: 'Qualification and convergence', tasks: ['T0901','T0902','T0903'] }] },
  ],
  tasks: [
    t({ id:'T0001', phase:'P00', objective:'Reconstruct exact live GitHub, ledger, state and claims', why:'Reasoning on stale authority is unsafe', status:'IMPLEMENTED_UNVERIFIED', owner:'Agentic Systems Architect', files:['control-plane/v2/state/live-truth.r2.json'], tests:['TST-CP-LIVE-TRUTH'], rollback:'Supersede the snapshot with a newer revision' }),
    t({ id:'T0002', phase:'P00', objective:'Create a unique session and bounded claim', why:'Concurrent agents need collision and death semantics', status:'IMPLEMENTED_UNVERIFIED', deps:['T0001'], owner:'Agentic Systems Architect', files:['control-plane/v2/sessions/**','control-plane/v2/claims/**'], tests:['TST-AGENT-COLLISION'], rollback:'Release the claim and append a handoff event' }),
    t({ id:'T0003', phase:'P00', objective:'Segment and validate the append-only event ledger', why:'Mutable documents cannot preserve causality', status:'IMPLEMENTED_UNVERIFIED', deps:['T0002'], owner:'Event-Sourcing Architect', files:['control-plane/v2/events/**'], tests:['TST-EVENT-SEQUENCE'], rollback:'Append a correcting event; never rewrite sealed segments' }),
    t({ id:'T0004', phase:'P00', objective:'Define the canonical V2 graph ontology and lexicon', why:'Shared IDs require shared semantics', status:'IMPLEMENTED_UNVERIFIED', deps:['T0001'], owner:'Knowledge Graph Engineer', files:['control-plane/v2/model/ontology.json','LEXICON.md'], tests:['TST-ONTOLOGY-REFS'], rollback:'Publish ontology vNext and supersede this version' }),
    t({ id:'T0005', phase:'P00', objective:'Materialize the temporal hypergraph and COS views', why:'Linear plans hide lateral, temporal and authority implications', status:'IMPLEMENTED_UNVERIFIED', deps:['T0004'], owner:'Graph Systems Architect', files:['control-plane/v2/model/hypergraph.json','control-plane/v2/generated/**'], tests:['TST-GRAPH-INTEGRITY'], rollback:'Delete generated projections and rebuild from model' }),
    t({ id:'T0006', phase:'P00', objective:'Implement and execute the zero-dependency validator/compiler', why:'Machine-readable state without executable checks still drifts', deps:['T0004','T0005'], owner:'Staff Software Engineer', files:['scripts/validate-v2-control-plane-v2.mjs','scripts/compile-v2-control-plane-v2.mjs'], tests:['TST-CP-VALIDATOR-SELF'], rollback:'Discard generated artifacts and retain source model' }),
    t({ id:'T0007', phase:'P00', objective:'Refresh root continuity surfaces from validated V2 state', why:'Current root documents point successors to stale work', deps:['T0006'], owner:'Documentation Architect', files:['README_FIRST.md','STATE.md','TASKS.md','HANDOFF.md','GRAPH.md','AGENTS.md'], tests:['TST-CP-DOC-DRIFT'], rollback:'Restore prior blobs and keep V2 state additive' }),
    t({ id:'T0008', phase:'P00', objective:'Synchronize GitHub, Drive and Todoist', why:'Cross-chat continuity requires all operational planes to agree', deps:['T0007'], owner:'Executive Operations Agent', tests:['TST-CROSS-PLANE-SYNC'], rollback:'Append a compensating checkpoint and record degraded connector state' }),
    t({ id:'T0101', phase:'P01', objective:'Preserve one reconciled Phase 01 lineage', why:'V2 must not reopen sibling divergence', status:'COMPLETE_STATIC_UNVERIFIED', owner:'Migration Architect', files:['docs/hardening/PHASE_01_CLOSURE.md'], rollback:'Return to the #33 checkpoint' }),
    t({ id:'T0201', phase:'P02', objective:'Preserve legacy evidence and deletion governance', why:'Refactors cannot erase regressions by rewriting tests', status:'COMPLETE_STATIC_UNVERIFIED', deps:['T0101'], owner:'Test Architect', files:['docs/hardening/TEST_EVIDENCE_MANIFEST.json','docs/hardening/DELETION_GOVERNANCE.json'], rollback:'Restore deleted paths from provenance refs' }),
    t({ id:'T0202', phase:'P02', objective:'Enforce one selected API surface and explicit compatibility states', why:'Multiple exports create hidden writers', status:'COMPLETE_STATIC_UNVERIFIED', deps:['T0201'], owner:'Developer Experience Architect', files:['docs/hardening/COMPATIBILITY_MATRIX.md'], tests:['TST-AUTHORITY-SURFACE-UNIQUE'], rollback:'Return to explicit selected subpath imports' }),
    t({ id:'T0301', phase:'P03', objective:'Execute core graph, identity, CAS and CSR invariants', why:'Static code cannot prove determinism or mutation safety', deps:['T0701'], owner:'Formal Methods Reviewer', risk:'CRITICAL', tests:['TST-CORE-INVARIANTS'], rollback:'Reject the candidate and preserve failure evidence' }),
    t({ id:'T0302', phase:'P03', objective:'Measure core graph performance scientifically', why:'Performance claims need distributions and reproducible environments', deps:['T0301','T0803'], owner:'Performance Engineer', tests:['TST-BENCH-SCIENTIFIC'], rollback:'Remove unsupported performance claims' }),
    t({ id:'T0401', phase:'P04', objective:'Execute event, bitemporal and persistence semantic parity', why:'Durable temporal truth is an authority prerequisite', deps:['T0701'], owner:'Event-Sourcing Architect', risk:'CRITICAL', tests:['TST-EVENT-PARITY','TST-BITEMPORAL'], rollback:'Restore the frozen Phase 03 checkpoint' }),
    t({ id:'T0402', phase:'P04', objective:'Prove corrupted-snapshot rejection and empty-database restore', why:'Recovery cannot remain conceptual', deps:['T0401'], owner:'Recovery Engineer', risk:'CRITICAL', tests:['TST-EMPTY-DB-RESTORE','TST-GRAPH-REBUILD'], rollback:'Restore the previous qualified snapshot and isolate the bad artifact' }),
    t({ id:'T0501', phase:'P05', objective:'Recompute and verify provider evidence before accepting observed outcomes', why:'A claimed evidence hash is not proof of evidence integrity', owner:'Security Architect', risk:'CRITICAL', files:['packages/execution/src/authority-observed-outcome-recorder.ts'], tests:['TST-PROVIDER-EVIDENCE-TAMPER'], rollback:'Remain reconciliation_required' }),
    t({ id:'T0502', phase:'P05', objective:'Implement bounded GitHub and Drive reconciliation adapters', why:'Generic contracts cannot close real timeout-after-acceptance ambiguity', deps:['T0501'], owner:'Adapter Engineer', risk:'CRITICAL', files:['packages/execution/src/providers/**'], tests:['TST-PROVIDER-TIMEOUT-AFTER-ACCEPT'], rollback:'Require manual reconciliation and prohibit retry' }),
    t({ id:'T0503', phase:'P05', objective:'Physically prove TLS pinning and atomic filesystem broker boundaries', why:'Decision objects alone do not enforce transport or TOCTOU safety', owner:'Security Engineer', risk:'CRITICAL', files:['packages/execution/src/platform/**'], tests:['TST-TLS-PINNING','TST-FS-TOCTOU'], rollback:'Disable affected authority capabilities' }),
    t({ id:'T0504', phase:'P05', objective:'Complete durable signal and telemetry repair', why:'Observation failure must be recoverable without changing protected truth', owner:'Observability Engineer', files:['packages/execution/**','packages/observability/**'], tests:['TST-OBS-SINK-DOWN'], rollback:'Retain degraded counter and require manual repair' }),
    t({ id:'T0505', phase:'P05', objective:'Prove concurrent writers, lease takeover, fencing and AgentRun recovery', why:'Single-process contracts do not prove multi-writer safety', deps:['T0701','T0501','T0504'], owner:'Distributed Systems Architect', risk:'CRITICAL', tests:['TST-CONTENTION','TST-PROCESS-KILL'], rollback:'Block autonomous side effects and authority promotion' }),
    t({ id:'T0601', phase:'P06', objective:'Prove one project-scoped GraphRAG and ContextPack path', why:'Agents require bounded evidence without cross-project leakage', deps:['T0701'], owner:'GraphRAG Engineer', risk:'CRITICAL', files:['packages/graph/**'], tests:['TST-CONTEXT-SCOPE'], rollback:'Use a manual bounded context packet' }),
    t({ id:'T0602', phase:'P06', objective:'Prove append-only epistemic and bitemporal memory semantics', why:'Current-row overwrite cannot answer what was known when', deps:['T0701'], owner:'Memory Systems Engineer', risk:'CRITICAL', files:['packages/memory/**'], tests:['TST-MEMORY-BITEMPORAL'], rollback:'Keep legacy memory non-authority and read-only' }),
    t({ id:'T0603', phase:'P06', objective:'Build a gold-query evaluation set across Hub, memory and GraphRAG', why:'Technically correct retrieval can still fail the operator goal', deps:['T0601','T0602'], owner:'Product Architect', files:['EVIDENCE/gold-queries/**'], tests:['TST-GOLD-QUERY'], rollback:'Make no product-quality claim' }),
    t({ id:'T0604', phase:'P06', objective:'Connect canonical paths to AuthorityTelemetry without a SPOF', why:'Authority paths require traceability and redaction', deps:['T0504'], owner:'Reliability Engineer', files:['packages/observability/**'], tests:['TST-TELEMETRY-E2E'], rollback:'Use failure-isolated Noop telemetry' }),
    t({ id:'T0701', phase:'P07', objective:'Pin toolchain and produce a reproducible clean install', why:'All assurance depends on reproducible dependencies and bytes', deps:['T0008'], owner:'DevSecOps Engineer', risk:'CRITICAL', files:['package-lock.json','EVIDENCE/toolchain/**'], tests:['TST-CLEAN-INSTALL'], rollback:'Restore the prior lockfile and record incompatibility' }),
    t({ id:'T0702', phase:'P07', objective:'Rebuild a manual-only full verification matrix', why:'Zero automatic spend must not reduce test breadth', deps:['T0701'], owner:'DevSecOps Engineer', risk:'CRITICAL', files:['.github/workflows/**'], tests:['TST-CI-FAIL-RED'], rollback:'Disable workflow_dispatch' }),
    t({ id:'T0703', phase:'P07', objective:'Execute legacy, authority, orphan, property and mutation suites', why:'Written tests and historical claims must be reconciled with reality', deps:['T0701','T0702'], owner:'Test Architect', risk:'CRITICAL', files:['EVIDENCE/tests/**'], tests:['TST-FULL-MATRIX'], rollback:'Do not promote; preserve every failure artifact' }),
    t({ id:'T0801', phase:'P08', objective:'Run the security threat-model and adversarial diff gauntlet', why:'Authority promotion requires explicit trust boundaries and residual risks', deps:['T0703','T0503'], owner:'CISO Reviewer', risk:'CRITICAL', files:['EVIDENCE/security/**'], tests:['TST-SECURITY-GAUNTLET'], rollback:'Block promotion and disable affected capability' }),
    t({ id:'T0802', phase:'P08', objective:'Execute replay, restore, failure injection and agent-death drills', why:'The system must survive component and context loss', deps:['T0402','T0505','T0601','T0602','T0703'], owner:'Recovery Engineer', risk:'CRITICAL', files:['EVIDENCE/recovery/**'], tests:['TST-RECOVERY-GAUNTLET','TST-COLD-AGENT-5MIN'], rollback:'Return to the last qualified checkpoint' }),
    t({ id:'T0803', phase:'P08', objective:'Run scientific performance and bottleneck analysis', why:'Optimize measured critical paths rather than imagined infrastructure', deps:['T0703'], owner:'Performance Engineer', files:['EVIDENCE/performance/**'], tests:['TST-PERFORMANCE'], rollback:'Remove unsupported performance claims' }),
    t({ id:'T0804', phase:'P08', objective:'Compile the evidence-linked D01–D20 scorecard', why:'Promotion must be mechanical rather than rhetorical', deps:['T0801','T0802','T0803'], owner:'Assurance Lead', risk:'CRITICAL', files:['SCORECARD_20D.md','EVIDENCE/scorecard.json'], tests:['TST-SCORE-PROMOTION'], rollback:'Restore the previous evidence-backed scorecard' }),
    t({ id:'T0901', phase:'P09', objective:'Perform final independent 20D adversarial review', why:'Self-review cannot authorize production authority', deps:['T0804'], owner:'Independent Senior Reviewer', risk:'CRITICAL', files:['REPORTS/final-20d-review.md'], tests:['TST-REVIEW-HEAD-SHA'], rollback:'Invalidate approval after any head change' }),
    t({ id:'T0902', phase:'P09', objective:'Create one reviewable main-convergence PR with rollback checkpoint', why:'Stacked drafts must not become production through an opaque merge', deps:['T0901'], owner:'Migration Architect', risk:'CRITICAL', tests:['TST-P09-LINEAGE'], rollback:'Revert the integration merge or restore the checkpoint branch' }),
    t({ id:'T0903', phase:'P09', objective:'Promote to AUTHORITY_READY and synchronize durable state', why:'Authority is an explicit lifecycle transition', deps:['T0902'], owner:'Roberto Gil Ortega', risk:'CRITICAL', files:['STATE.md','HANDOFF.md','control-plane/v2/events/**'], tests:['TST-AUTHORITY-PROMOTION'], rollback:'Append a demotion event and restore the previous checkpoint' }),
  ],
  currentExecutableFrontier: ['T0006','T0501'],
  parallelization: [
    { lane:'A', tasks:['T0006','T0007','T0008'], exclusiveScopes:['control-plane/v2/**','root continuity documents'] },
    { lane:'B', tasks:['T0501'], exclusiveScopes:['packages/execution/src/authority-observed-outcome-recorder.ts'], startCondition:'separate session, claim and branch from exact PR #54 head' },
    { lane:'C', tasks:['T0502'], exclusiveScopes:['packages/execution/src/providers/**'], startCondition:'T0501 contract frozen' },
    { lane:'D', tasks:['T0503'], exclusiveScopes:['packages/execution/src/platform/**'], startCondition:'trusted platform executor available' },
  ],
};

export default program;
